[connection]
address = "0.0.0.0"
port = 25565
compression_threshold = 0
# sets a protocol version where the player will be locked into the lobby
# and only allowed to teleport to unrestricted servers
# set to -1 to disable, requires player_validation to be enabled
minimum_protocol_version = -1
minimum_version_name = ""
# set whether the server should authenticate with mojang servers
# required for proxy support
online = true

[ping]
motd = "<green>DFLobbyServer"
fake_max_players = -1
show_online_players = true
favicon_path = "icon.png"

# settings for proxy connection
# "proxy" can be one of the following
# - "velocity" or "gate"
#  -  connects to the velocity proxy.
#  -  requires "secret" to be set.
#  -  required "online" to be set to "false" in "connection"
# - "none"
#  -  no proxy.
[proxy]
proxy = "none"
secret = ""
messaging_channel = "BungeeCord"
expect_channel_response = false
# checks the incompatibility of the client and the real protocol version
# before the player is allowed to join other servers
# requires df:proxy channel to be used (or DFProxyPlugin)
player_validation = false

[lobby]
spawn = {x = 0.0, y = 100.0, z = 0.0}
world = "worlds/world"

[minigames.parkour]
enabled = true
respawn = {x = 0.0, y = 0.0, z = 0.0, yaw = 0.0, pitch = 0.0}

[minigames.nether]
enabled = false
world = "worlds/world_nether"
combat_enabled = false
portal_in_nether_location = {x = 0.0, y = 0.0, z = 0.0}
portal_in_overworld_location = {x = 0.0, y = 0.0, z = 0.0}
spawn_location = {x = 0.0, y = 0.0, z = 0.0}
portal_location = {x = 0.0, y = 0.0, z = 0.0}

[servers]
    [[servers.servers]]
    name = "UnrestrictedExample"
    server = "example0"
    unrestricted = true
#
#    [[server.server]]
#    entity = "creeper"
#    name = "UnrestrictedExampleWithEntity"
#    position = {x = 120.5, y = 4.0, z = 73.5, yaw = 180.0}
#    server = "example1"
#    unrestricted = true

    [[servers.servers]]
    entity = "zombie"
    name = "RestrictedExample"
    position = {x = 118.5, y = 4.0, z = 73.5, yaw = 180.0}
    server = "example2"

    [[servers.servers]]
    entity = "bamboo_raft"
    name = ""
    server = "example3_noname"
    position = {x = 102.0, y = 1.2, z = 55.0, yaw = 180.0}

[admins]
by_username = ["realusernamethatmojang100%allowsyoutohaveanduseinminecraftjavaeditiontrust"]